In [1]:
# Import all the required libraries
import pandas as pd

In [2]:
# read the dataset
dataset1=pd.read_csv("../../../final_mob_dataset.csv",index_col=None)

In [3]:
# copy the dataset to df2
df2=dataset1

In [4]:
# Print the dataset
df2

,product id,price,sale,weight,resolution,ppi,cpu core,cpu freq,internal mem,ram,rearcam,front cam,battery,thickness
0,203,2357,10.0,135.0,5.20,424.0,8,1.350,16.0,3.000,13.00,8.0,2610,7.4
1,880,1749,10.0,125.0,4.00,233.0,2,1.300,4.0,1.000,3.15,0.0,1700,9.9
2,40,1916,10.0,110.0,4.70,312.0,4,1.200,8.0,1.500,13.00,5.0,2000,7.6
3,99,1315,11.0,118.5,4.00,233.0,2,1.300,4.0,0.512,3.15,0.0,1400,11.0
4,880,1749,11.0,125.0,4.00,233.0,2,1.300,4.0,1.000,3.15,0.0,1700,9.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,1206,3551,899.5,178.0,5.46,538.0,4,1.875,68.0,6.000,12.00,16.0,4080,8.4
157,1296,3211,899.5,170.0,5.50,534.0,4,1.975,68.0,6.000,20.00,8.0,3400,7.9
158,856,3260,899.5,150.0,5.50,401.0,8,2.200,64.0,4.000,20.00,20.0,3000,6.8
159,1296,3211,899.5,170.0,5.50,534.0,4,1.975,68.0,6.000,20.00,8.0,3400,7.9
160,1131,2536,899.5,202.0,6.00,367.0,8,1.500,16.0,3.000,21.50,16.0,2700,8.4

In [5]:
# Convert the categorical data to numerical data using get_dummies
df2 = pd.get_dummies(df2, drop_first=True,dtype= int)

In [6]:
# print the updated data
df2

,product id,price,sale,weight,resolution,ppi,cpu core,cpu freq,internal mem,ram,rearcam,front cam,battery,thickness
0,203,2357,10.0,135.0,5.20,424.0,8,1.350,16.0,3.000,13.00,8.0,2610,7.4
1,880,1749,10.0,125.0,4.00,233.0,2,1.300,4.0,1.000,3.15,0.0,1700,9.9
2,40,1916,10.0,110.0,4.70,312.0,4,1.200,8.0,1.500,13.00,5.0,2000,7.6
3,99,1315,11.0,118.5,4.00,233.0,2,1.300,4.0,0.512,3.15,0.0,1400,11.0
4,880,1749,11.0,125.0,4.00,233.0,2,1.300,4.0,1.000,3.15,0.0,1700,9.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,1206,3551,899.5,178.0,5.46,538.0,4,1.875,68.0,6.000,12.00,16.0,4080,8.4
157,1296,3211,899.5,170.0,5.50,534.0,4,1.975,68.0,6.000,20.00,8.0,3400,7.9
158,856,3260,899.5,150.0,5.50,401.0,8,2.200,64.0,4.000,20.00,20.0,3000,6.8
159,1296,3211,899.5,170.0,5.50,534.0,4,1.975,68.0,6.000,20.00,8.0,3400,7.9
160,1131,2536,899.5,202.0,6.00,367.0,8,1.500,16.0,3.000,21.50,16.0,2700,8.4

In [7]:
# Get independent and dependent variables
indep_X=df2.drop(columns='price', axis=1)
dep_Y=df2['price']

In [8]:
# Print the indep_X
indep_X

,product id,sale,weight,resolution,ppi,cpu core,cpu freq,internal mem,ram,rearcam,front cam,battery,thickness
0,203,10.0,135.0,5.20,424.0,8,1.350,16.0,3.000,13.00,8.0,2610,7.4
1,880,10.0,125.0,4.00,233.0,2,1.300,4.0,1.000,3.15,0.0,1700,9.9
2,40,10.0,110.0,4.70,312.0,4,1.200,8.0,1.500,13.00,5.0,2000,7.6
3,99,11.0,118.5,4.00,233.0,2,1.300,4.0,0.512,3.15,0.0,1400,11.0
4,880,11.0,125.0,4.00,233.0,2,1.300,4.0,1.000,3.15,0.0,1700,9.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,1206,899.5,178.0,5.46,538.0,4,1.875,68.0,6.000,12.00,16.0,4080,8.4
157,1296,899.5,170.0,5.50,534.0,4,1.975,68.0,6.000,20.00,8.0,3400,7.9
158,856,899.5,150.0,5.50,401.0,8,2.200,64.0,4.000,20.00,20.0,3000,6.8
159,1296,899.5,170.0,5.50,534.0,4,1.975,68.0,6.000,20.00,8.0,3400,7.9
160,1131,899.5,202.0,6.00,367.0,8,1.500,16.0,3.000,21.50,16.0,2700,8.4

In [9]:
# Print the dep_Y
dep_Y

0      2357
1      1749
2      1916
3      1315
4      1749
       ...
156    3551
157    3211
158    3260
159    3211
160    2536
Name: price, Length: 161, dtype: int64

In [10]:
# import regression related methods from PCA_regression
from PCA_regression import *

In [11]:
# Split the train and test data
X_train, X_test, y_train, y_test=split_scalar(indep_X,dep_Y)

In [12]:
# Get training and test data from PCA
X_train, X_test=PCA(X_train,X_test,2)

[0.52445874 0.11885473]

In [13]:
# Create empty list to store accuracy for each algorithms
acclin=[]
accsvml=[]
accsvmnl=[]
accdes=[]
accrf=[]

In [14]:
# Get all the required details from each algorithm and assign the R2 score to the respective list
r2_lin=Linear(X_train,y_train,X_test, y_test)
acclin.append(r2_lin)

r2_sl=svm_linear(X_train,y_train,X_test, y_test)    
accsvml.append(r2_sl)

r2_NL=svm_NL(X_train,y_train,X_test, y_test)
accsvmnl.append(r2_NL)

r2_d=Decision(X_train,y_train,X_test, y_test)
accdes.append(r2_d)

r2_r=random_forest(X_train,y_train,X_test, y_test)
accrf.append(r2_r)

In [24]:
# get all the r2 score of each algorithm and print it in a dataframe
result=pca_regression(acclin,accsvml,accsvmnl,accdes,accrf,7)

In [16]:
# result of  n=4
result

         Linear      SVMl    SVMnl  Decision    Random
pca:4  0.866084  0.726018  0.02443  0.956784  0.939816

In [19]:
result

         Linear      SVMl    SVMnl  Decision    Random
pca:5  0.866084  0.726018  0.02443  0.956784  0.939816

In [22]:
result

         Linear      SVMl    SVMnl  Decision    Random
pca:6  0.866084  0.726018  0.02443  0.956784  0.939816

In [25]:
result

         Linear      SVMl    SVMnl  Decision    Random
pca:7  0.866084  0.726018  0.02443  0.956784  0.939816