In [1]:
# Imports all the libraries
import pandas as pd

In [2]:
# read the dataset
dataset1=pd.read_csv("../../final_mob_dataset.csv",index_col=None)

In [3]:
# copy the dataset to df2
df2=dataset1

In [4]:
# Print the dataset
df2

,product id,price,sale,weight,resolution,ppi,cpu core,cpu freq,internal mem,ram,rearcam,front cam,battery,thickness
0,203,2357,10.0,135.0,5.20,424.0,8,1.350,16.0,3.000,13.00,8.0,2610,7.4
1,880,1749,10.0,125.0,4.00,233.0,2,1.300,4.0,1.000,3.15,0.0,1700,9.9
2,40,1916,10.0,110.0,4.70,312.0,4,1.200,8.0,1.500,13.00,5.0,2000,7.6
3,99,1315,11.0,118.5,4.00,233.0,2,1.300,4.0,0.512,3.15,0.0,1400,11.0
4,880,1749,11.0,125.0,4.00,233.0,2,1.300,4.0,1.000,3.15,0.0,1700,9.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,1206,3551,899.5,178.0,5.46,538.0,4,1.875,68.0,6.000,12.00,16.0,4080,8.4
157,1296,3211,899.5,170.0,5.50,534.0,4,1.975,68.0,6.000,20.00,8.0,3400,7.9
158,856,3260,899.5,150.0,5.50,401.0,8,2.200,64.0,4.000,20.00,20.0,3000,6.8
159,1296,3211,899.5,170.0,5.50,534.0,4,1.975,68.0,6.000,20.00,8.0,3400,7.9
160,1131,2536,899.5,202.0,6.00,367.0,8,1.500,16.0,3.000,21.50,16.0,2700,8.4

In [5]:
# Convert the categorical data to numerical data using get_dummies
df2 = pd.get_dummies(df2, drop_first=True,dtype= int)

In [6]:
# print the updated data
df2

,product id,price,sale,weight,resolution,ppi,cpu core,cpu freq,internal mem,ram,rearcam,front cam,battery,thickness
0,203,2357,10.0,135.0,5.20,424.0,8,1.350,16.0,3.000,13.00,8.0,2610,7.4
1,880,1749,10.0,125.0,4.00,233.0,2,1.300,4.0,1.000,3.15,0.0,1700,9.9
2,40,1916,10.0,110.0,4.70,312.0,4,1.200,8.0,1.500,13.00,5.0,2000,7.6
3,99,1315,11.0,118.5,4.00,233.0,2,1.300,4.0,0.512,3.15,0.0,1400,11.0
4,880,1749,11.0,125.0,4.00,233.0,2,1.300,4.0,1.000,3.15,0.0,1700,9.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,1206,3551,899.5,178.0,5.46,538.0,4,1.875,68.0,6.000,12.00,16.0,4080,8.4
157,1296,3211,899.5,170.0,5.50,534.0,4,1.975,68.0,6.000,20.00,8.0,3400,7.9
158,856,3260,899.5,150.0,5.50,401.0,8,2.200,64.0,4.000,20.00,20.0,3000,6.8
159,1296,3211,899.5,170.0,5.50,534.0,4,1.975,68.0,6.000,20.00,8.0,3400,7.9
160,1131,2536,899.5,202.0,6.00,367.0,8,1.500,16.0,3.000,21.50,16.0,2700,8.4

In [7]:
# Get independent and dependent variables
indep_X=df2.drop(columns='price', axis=1)
dep_Y=df2['price']

In [8]:
# Print the indep_X
indep_X

,product id,sale,weight,resolution,ppi,cpu core,cpu freq,internal mem,ram,rearcam,front cam,battery,thickness
0,203,10.0,135.0,5.20,424.0,8,1.350,16.0,3.000,13.00,8.0,2610,7.4
1,880,10.0,125.0,4.00,233.0,2,1.300,4.0,1.000,3.15,0.0,1700,9.9
2,40,10.0,110.0,4.70,312.0,4,1.200,8.0,1.500,13.00,5.0,2000,7.6
3,99,11.0,118.5,4.00,233.0,2,1.300,4.0,0.512,3.15,0.0,1400,11.0
4,880,11.0,125.0,4.00,233.0,2,1.300,4.0,1.000,3.15,0.0,1700,9.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,1206,899.5,178.0,5.46,538.0,4,1.875,68.0,6.000,12.00,16.0,4080,8.4
157,1296,899.5,170.0,5.50,534.0,4,1.975,68.0,6.000,20.00,8.0,3400,7.9
158,856,899.5,150.0,5.50,401.0,8,2.200,64.0,4.000,20.00,20.0,3000,6.8
159,1296,899.5,170.0,5.50,534.0,4,1.975,68.0,6.000,20.00,8.0,3400,7.9
160,1131,899.5,202.0,6.00,367.0,8,1.500,16.0,3.000,21.50,16.0,2700,8.4

In [9]:
# Print the dep_Y
dep_Y

0      2357
1      1749
2      1916
3      1315
4      1749
       ...
156    3551
157    3211
158    3260
159    3211
160    2536
Name: price, Length: 161, dtype: int64

In [10]:
# import regression related methods from feature_importance_regression
from feature_importance_regression import *

In [43]:
# get best features
ensemble_feature_list=permutation_feature_importance(indep_X,dep_Y,8, df2.columns)

LinearRegression()
Selected top 8 features index [12  4  3  8  7  5 11  2] for LinearRegression()
battery : 0.143 +/- 0.007
resolution: 0.117 +/- 0.010
weight  : 0.111 +/- 0.013
internal mem: 0.106 +/- 0.014
cpu freq: 0.063 +/- 0.009
ppi     : 0.050 +/- 0.003
front cam: 0.040 +/- 0.003
sale    : 0.037 +/- 0.002
Selected top 8 features ['battery', 'resolution', 'weight', 'internal mem', 'cpu freq', 'ppi', 'front cam', 'sale'] for LinearRegression()
SVR(kernel='linear')
Selected top 8 features index [ 4 11  7  5 12 10  8  2] for SVR(kernel='linear')
resolution: 0.289 +/- 0.029
front cam: 0.099 +/- 0.005
cpu freq: 0.096 +/- 0.013
ppi     : 0.033 +/- 0.005
battery : 0.030 +/- 0.004
rearcam : 0.010 +/- 0.004
internal mem: 0.006 +/- 0.002
sale    : 0.004 +/- 0.002
Selected top 8 features ['resolution', 'front cam', 'cpu freq', 'ppi', 'battery', 'rearcam', 'internal mem', 'sale'] for SVR(kernel='linear')
DecisionTreeRegressor(random_state=0)
Selected top 8 features index [ 8  4 12  3  7 10  6  9] for DecisionTreeRegressor(random_state=0)
internal mem: 0.917 +/- 0.093
resolution: 0.154 +/- 0.018
battery : 0.146 +/- 0.013
weight  : 0.123 +/- 0.031
cpu freq: 0.112 +/- 0.011
rearcam : 0.062 +/- 0.008
cpu core: 0.034 +/- 0.003
ram     : 0.017 +/- 0.003
Selected top 8 features ['internal mem', 'resolution', 'battery', 'weight', 'cpu freq', 'rearcam', 'cpu core', 'ram'] for DecisionTreeRegressor(random_state=0)
RandomForestRegressor(n_estimators=10, random_state=0)
Selected top 8 features index [ 8  4 12  7 11  6 10  5] for RandomForestRegressor(n_estimators=10, random_state=0)
internal mem: 0.430 +/- 0.038
resolution: 0.100 +/- 0.012
battery : 0.070 +/- 0.012
cpu freq: 0.067 +/- 0.011
front cam: 0.015 +/- 0.001
cpu core: 0.013 +/- 0.002
rearcam : 0.011 +/- 0.001
ppi     : 0.010 +/- 0.001
Selected top 8 features ['internal mem', 'resolution', 'battery', 'cpu freq', 'front cam', 'cpu core', 'rearcam', 'ppi'] for RandomForestRegressor(n_estimators=10, random_state=0)
feature_list::  ['battery', 'resolution', 'weight', 'internal mem', 'cpu freq', 'ppi', 'front cam', 'sale', 'resolution', 'front cam', 'cpu freq', 'ppi', 'battery', 'rearcam', 'internal mem', 'sale', 'internal mem', 'resolution', 'battery', 'weight', 'cpu freq', 'rearcam', 'cpu core', 'ram', 'internal mem', 'resolution', 'battery', 'cpu freq', 'front cam', 'cpu core', 'rearcam', 'ppi']

In [44]:
# print selected features
ensemble_feature_list

['ppi',
 'cpu core',
 'sale',
 'internal mem',
 'resolution',
 'front cam',
 'battery',
 'rearcam',
 'weight',
 'ram',
 'cpu freq']

In [45]:
# Create empty list to store accuracy for each algorithms
acclin=[]
accsvml=[]
accsvmnl=[]
accdes=[]
accrf=[]

In [46]:
# Get all the required details from each algorithm and assign the R2 score to the respective list
  
X_train, X_test, y_train, y_test=split_scalar(indep_X[ensemble_feature_list],dep_Y)  
r2_lin=Linear(X_train,y_train,X_test,y_test)
acclin.append(r2_lin)

r2_sl=svm_linear(X_train,y_train,X_test,y_test)    
accsvml.append(r2_sl)

r2_NL=svm_NL(X_train,y_train,X_test,y_test)
accsvmnl.append(r2_NL)

r2_d=Decision(X_train,y_train,X_test,y_test)
accdes.append(r2_d)

r2_r=random_forest(X_train,y_train,X_test,y_test)
accrf.append(r2_r)

In [47]:
# get all the accuracy of each algorithm and print it in a dataframe
result=feature_importance_regression(acclin,accsvml,accsvmnl,accdes,accrf)

In [41]:
# result of  k = 5
result

            Linear      SVMl    SVM_NL Decision    Random
R2 score  0.779411  0.553144  0.008041  0.82139  0.901348

In [36]:
# result of  k = 6
result

            Linear      SVMl    SVM_NL  Decision    Random
R2 score  0.866189  0.672839  0.013144  0.695935  0.939067

In [42]:
# result of  k = 7
result

           Linear      SVMl    SVM_NL Decision    Random
R2 score  0.86392  0.678496  0.009468  0.89119  0.935865

In [48]:
# result of  k = 8
result

            Linear      SVMl    SVM_NL  Decision    Random
R2 score  0.885651  0.732562  0.010548  0.959535  0.923341

In [16]:
# result of  k = 9
result

            Linear      SVMl    SVM_NL  Decision   Random
R2 score  0.880266  0.736396  0.006477  0.886926  0.90763